package com.travelassistant.backend.application.assistant

enum class HotelSearchPreferencesPatchIssue {
    INVALID_MAX_TOTAL_PRICE,
    UNSUPPORTED_MAX_TOTAL_PRICE_CURRENCY,
    INVALID_STARS,
    INVALID_MINIMUM_GUEST_RATING,
    INVALID_FREE_CANCELLATION_REQUIREMENT,
    INVALID_BREAKFAST_REQUIREMENT,
}
