import { TOOL_VERSION } from "./paths.js";
import { buildEndpointReports } from "./placeholder-policy.js";
import type {
  CheckReport,
  ConformanceReport,
  Finding,
  OpenApiInventory,
  RuntimeRoute,
} from "./types.js";
import type { SubsetManifestState } from "./subset-manifest.js";

export function buildReport(
  openApiInventory: OpenApiInventory,
  runtimeRoutes: RuntimeRoute[],
  subsetManifest: SubsetManifestState,
): ConformanceReport {
  const endpoints = buildEndpointReports(openApiInventory.operations, runtimeRoutes);
  const advisoryFindings: Finding[] = [
    {
      code: "GENERATED_CLIENT_READY_SUBSET_MISSING",
      severity: "advisory",
      message:
        "Generated-client-ready subset manifest is not created; this is expected for the skeleton and keeps readiness not_ready.",
    },
    {
      code: "STATIC_RUNTIME_ROUTE_SCAN",
      severity: "advisory",
      message:
        "Runtime route inventory is collected by conservative static Ktor source scanning; no backend server was started.",
    },
    {
      code: "PLACEHOLDER_ENDPOINTS_EXCLUDED",
      severity: "advisory",
      message:
        "Hotel search, offers, shortlist, and explanation placeholder endpoints remain excluded and are not generated-client-ready.",
    },
  ];

  const futureOnlyChecks = buildFutureOnlyChecks();

  return {
    tool: {
      name: "travel-assistant-openapi-conformance",
      version: TOOL_VERSION,
      mode: "classification",
      readOnly: true,
    },
    generatedAt: new Date().toISOString(),
    status: "not_ready",
    readinessClaim: false,
    openApiSource: {
      path: openApiInventory.sourcePath,
      detected: true,
      openApiVersion: openApiInventory.openApiVersion,
      serverBasePath: openApiInventory.serverBasePath,
      operationCount: openApiInventory.operations.length,
      candidates: openApiInventory.detectedFromCandidates,
    },
    subsetManifest,
    inventories: {
      openApi: openApiInventory.operations,
      runtimeRoutes,
    },
    endpoints,
    checks: buildChecks(openApiInventory, runtimeRoutes, subsetManifest),
    blockingFindings: [],
    advisoryFindings,
    futureOnlyChecks,
  };
}

function buildChecks(
  openApiInventory: OpenApiInventory,
  runtimeRoutes: RuntimeRoute[],
  subsetManifest: SubsetManifestState,
): CheckReport[] {
  return [
    {
      name: "openapi_source_detection",
      status: "passed",
      summary: `Detected OpenAPI source at ${openApiInventory.sourcePath}.`,
    },
    {
      name: "openapi_minimal_structure",
      status: "passed",
      summary: `Parsed OpenAPI ${openApiInventory.openApiVersion} with ${openApiInventory.operations.length} operations.`,
    },
    {
      name: "runtime_route_inventory",
      status: runtimeRoutes.length > 0 ? "advisory" : "missing",
      summary:
        runtimeRoutes.length > 0
          ? `Collected ${runtimeRoutes.length} runtime routes by static source scan.`
          : "No runtime routes were detected by static source scan.",
    },
    {
      name: "subset_manifest",
      status: subsetManifest.exists ? "advisory" : "not_created",
      summary: subsetManifest.exists
        ? "Subset manifest exists but is not enforced by the skeleton."
        : "Subset manifest is missing/not_created and is optional for this skeleton.",
    },
    {
      name: "readiness_status",
      status: "not_ready",
      summary:
        "Report status is intentionally not_ready; generated-client/OpenAPI readiness is not claimed.",
    },
  ];
}

function buildFutureOnlyChecks(): CheckReport[] {
  return [
    {
      name: "generated_client_generation",
      status: "future_only",
      summary: "Generated clients are not generated by this skeleton.",
    },
    {
      name: "generated_client_compile",
      status: "not_run",
      summary:
        "Generated-client compile check is future-only and was not run.",
    },
    {
      name: "runtime_http_contract_tests",
      status: "not_run",
      summary:
        "Runtime HTTP contract tests are future-only and were not run.",
    },
    {
      name: "full_openapi_finalization_gate",
      status: "future_only",
      summary:
        "Full OpenAPI finalization remains blocked by missing real hotel search/resource behavior.",
    },
  ];
}
